server.port = 8081
spring.application.name=Inventories

spring.datasource.url = jdbc:mysql://localhost:3306/comex_inventory
spring.datasource.username = root
spring.datasource.password = Lenoleoncito

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

# Token de seguridad
spring.secret.key = 7e1981b0b9b6d8fd97a223d09f5a1d8a32f2faa47cf875cfd95e7773ad0ee379

# Time Expiration
spring.time.expiration = 86400000